from .ade20k_sceneparse150 import ADE20KSceneParse150
from .afhq import AFHQ
from .celebahq import CelebAHQ
from .celebamask_hq import CelebAMaskHQ
from .coco2014_captions import COCO2014Captions
from .danbooru2019_portraits import Danbooru2019Portraits
from .dreambooth import DreamBooth
from .dsine_normal_eval import DSINENormalEval
from .ffhq import FFHQ
from .hypersim import Hypersim
from .iharmony4 import iHarmony4
from .imagenet import ImageNet
from .marigold_depth_eval import MarigoldDepthEval
from .places365 import Places365
from .raindrop import Raindrop
